### ISSUE TITLE
postcss/autoprefix bug

### ISSUE THREAD

**Issue by transtone** [vuejs/vue-cli#1042]
### Version
3.0.0-beta.6

### Steps to reproduce
system: macos-10.13.2

1. vue create myapp start a project, with pwa & typescript, no eslint & test.
2. write css in src/assets/style.css
3. add `import "@/assets/style.css"` in `main.ts`
4. yarn add  postcss-import
add `"postcss-import": {}` to `.postcssrc` 
5. when use `yarn serve`, the autoprefixer works fine. It shows in chrome's inspector.
6. yarn build
7. `app.xxx.css` in `dist` not add prefix automaticly 

### What is expected?
```css
.test{
    -webkit-transform:scaleY(.5);
    transform:scaleY(.5)
}
```

### What is actually happening?
```css
.test {
    transform:scaleY(.5)
}
```

doc here
https://github.com/vuejs/vue-cli/blob/dev/docs/css.md
can't solve the problem.
it says:
`Vue CLI uses PostCSS internally, and enables autoprefixer by default. You can configure PostCSS via .postcssrc or any config source supported by postcss-load-config.`
but autoprefixer not work, and change configure in config files (.postcssrc, .postcssrc.js, .postcssrc.json etc) not work.

this is a repo:
https://github.com/transtone/cli-server-test/tree/master
