### ISSUE TITLE
CSS background images 路径找不到

### ISSUE THREAD

**Issue by eightfeet** [vuejs/vue-cli#112]
用脚手架build prd时出现dist下css文件background-image找不到路径的情况，生成目录如下
```
|------dist
|------|------static
|------|------|-----css
|------|------|------|------app.436040cbfa6aab8cd7ca62e837db8eea.css
|------|------|------js
|------|------|------img
|------|------|------|------mix.a3cf3e7.png
|------|------index.html
```
生成css如下
```css
.mainbg{
    background-image:url(/static/img/mix.a3cf3e7.png);
}
```
导致url路径找不到
理想状态应该是这样才能找到
background-image:url(../img/mix.a3cf3e7.png);
怎么破
