### ISSUE TITLE
background-image doesn't work in *.module.less but work in *.module.css

### ISSUE THREAD

**Issue by zlab** [vuejs/vue-cli#1379]
### Version
3.0.0-beta.11

### Reproduction link
no

#### file structure
```
-- assets
--    bg-login.svg
-- login.js
-- login.module.css
-- login.module.less
```

#### login.module.css
``` css
.login {
    background-image: url('./assets/bg-login.svg');
}
```
### What is expected?
show the background image

### What is actually happening?
```
This dependency was not found:

* assets/bg-login.svg

To install it, you can run: npm install --save assets/bg-login.svg
```
---
