### ISSUE TITLE
Cannot deploy on AWS CodeBuild

### ISSUE THREAD

**Issue by ffxsam** [vuejs/vue-cli#1771]
### Version
3.0.0-rc.3

### Reproduction link
[https://pastebin.com/mxNqnQ14](https://pastebin.com/mxNqnQ14)

### Steps to reproduce
Deploy a fresh app to AWS CodeBuild (via CodePipeline).

### What is expected?
Build would work

### What is actually happening?
Build stage fails:

> onspot-v2@0.2.0 build /codebuild/output/src080882672/src
> vue-cli-service build

 ERROR  You are using Node v7.0.0, but vue-cli-service requires Node >=8.
Please upgrade your Node version.

---
We don't have fine-grained control to upgrade Node in a CodeBuild container. Could this requirement be adjusted in any way?

**Comment by LinusBorg** [comment]
No, I don't think so. 

The whole codebase is written with async/await, which isn't supported below node 8

**Comment by ffxsam** [comment]
Sorry, posted too soon without more research. AWS CodeBuild has a 8.11.0 container. Just had to change the image:

```yaml
      Environment:
        ComputeType: "BUILD_GENERAL1_SMALL"
        Image: "aws/codebuild/nodejs:8.11.0"
```
