### ISSUE TITLE
hot reload过程中vue.js的updateAttrs方法报错

### ISSUE THREAD

**Issue by unknown-coder** [vuejs/vue-cli#203]
![image](https://cloud.githubusercontent.com/assets/9328734/19542352/0dc30fc4-96a0-11e6-81f4-026d596402ee.png)
### 重现方法
- `npm run dev`
- 在`style`中写一个未定义过的className

``` css
.test {
  height: 100px;
  width: 100px;
  background-color: red;
}
```
- 在`template`中加一个`div`

``` html
<div class="test"></div>
```
- 保存，然后控制台报错，hot reload随之挂掉
### 似乎是有新定义的样式，写进template中时，会报错

@yyx990803
