### ISSUE TITLE
Importing a SCSS file into a Scss file with indented syntax is no longer working

### ISSUE THREAD

**Issue by rhinel** [vuejs/vue-cli#2123]
### Version
3.0.0-rc.11

### Node and OS info
Node v9.11.2, Yarn 1.9.4, macOS 10.13.6

### Steps to reproduce
Install this simple test-case and run yarn serve:

https://github.com/rhinel/vue-cli-issue-scss-import-scss

### What is expected?
In projects created with Vue CLI 3-rc-10, these @import statements were working without problems.

this result like this:

```css
#nav {
  padding: 30px;
}
#nav a {
  font-weight: bold;
  color: #2c3e50;
}
#nav a.router-link-exact-active {
  color: #42b983;
}
```

### What is actually happening?
the result like this:

```css
#nav {
  padding: 30px;
  a {
    font-weight: bold;
    color: #2c3e50;
    &.router-link-exact-active {
      color: #42b983;
    }
  }
}
```

---
thanks.
