### ISSUE TITLE
`@` shortcut not working in css files

### ISSUE THREAD

**Issue by katerlouis** [vuejs/vue-cli#2148]
### Version
3.0.0-rc.12

### Node and OS info
npm 6.3.0 / node 10.7.0

### Steps to reproduce
folder structure:
```
src
    assets
         arrow-right.svg

    styles
        main.less

    App.vue
```

### What is expected?
No error

### What is actually happening?
```

Failed to compile.

./src/App.vue?vue&type=style&index=0&lang=less& (./node_modules/css-loader??ref--10-oneOf-1-1!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/postcss-loader/lib??ref--10-oneOf-1-2!./node_modules/less-loader/dist/cjs.js??ref--10-oneOf-1-3!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/App.vue?vue&type=style&index=0&lang=less&) Module not found: Error: Can't resolve './styles/@/assets/fonts/TeleGroteskNext-Bold.ttf' in '/Users/reneeschke/projects/myproject/src'
```

---
```css
// main.less located in /src/styles
.foo {
    background-image: url(../assets/arrow-right.svg); // working
}

.bar {
    background-image: url(@/assets/arrow-right.svg); // NOT working
}
```

whereas @ works in a vue-component (App.vue or any other component, located no matter where)
```htlm
<img src="@/assets/arrow-right.svg" />
```
