### ISSUE TITLE
Vue-cli parallelism error at building when CPU limitations

### ISSUE THREAD

**Issue by JFGHT** [vuejs/vue-cli#2208]
### Version
3.0.0

### Node and OS info
Yarn 1.9.4 / CircleCI docker img: circleci/node:10.8-stretch-browsers

### Steps to reproduce
- Use the free version of CircleCI.
- Build with CircleCI.

### What is expected?
Normal build

### What is actually happening?
events.js:183
      throw er; // Unhandled 'error' event
      ^
Error: This socket has been ended by the other party
    at Socket.writeAfterFIN (...)

---
Deactivating the parallelism is a workaround. More info here: https://forum.vuejs.org/t/solution-to-building-error-in-circleci-or-any-other-machine-with-cpu-limitations/40862

I think this should be in the docs.

**Comment by yyx990803** [comment]
Not sure if that's the real cause as our own tests run on free Circle CI.

**Comment by JFGHT** [comment]
Are you able to reproduce it?

**Comment by sodatea** [comment]
As quoted [here](https://github.com/facebook/create-react-app/issues/4870#issuecomment-412658412):
> The issue with this on Dockerized services such as CircleCI is that the container thinks it has access to all of the hosts cores, although its being limited down to 4 by another process.

I've encountered this issue before, with jest.

**Comment by yyx990803** [comment]
@JFGHT Vue CLI's own tests runs on Circle CI free tier all the time, and it is passing right now. The only thing I can think of is that we are open source so we get 4 containers by default. Are you building from a private repo? In addition, can you share your Circle CI `config.yaml`?

One obvious option is disabling parallel by default in CI environments, although I'd like to avoid that if possible, as that would lead to non-optimal performance in CI systems that do support multiple cores.

**Comment by JFGHT** [comment]
Yes, I'm building in a private repo.

```
# Javascript Node CircleCI 2.0 configuration file
#
# @see https://circleci.com/docs/2.0/language-javascript/
#
version: 2

defaults: &defaults
  working_directory: ~/bloqify/generic
  docker:
  - image: circleci/node:10.8-stretch-browsers
    environment:
      JEST_SUITE_NAME: jest
      JEST_JUNIT_OUTPUT: artefacts/tests/jest/js-test-results.xml

upgrade_os: &upgrade_os
  run:
    name: Update OS
    command: sudo apt-get update && sudo apt-get install

upgrade_yarn: &upgrade_yarn
  run:
    name: Update Yarn
    command: sudo npm i -g yarn

yarn_install: &yarn_install
  run:
    name: Yarn install
    command: yarn install --frozen-lockfile --non-interactive

inspect_webpack_config: &inspect_webpack_config
  run:
    name: Inspect Webpack config
    command: yarn inspect

yarn_build: &yarn_build
  run:
    name: Yarn build
    command: yarn build

yarn_test: &yarn_test
  run:
    name: Run tests
    command: yarn test:unit --ci --runInBand --reporters="default" --reporters="jest-junit"

eslint_junit: &eslint_junit
  run:
    name: ESlint
    command: ./node_modules/.bin/eslint ./src/**/*.{js,ts}  --format junit --output-file ./artefacts/eslint/js-lint-results.xml

cloud_functions_yarn_install: &cloud_functions_yarn_install
  run:
    name: Install Cloud Functions dependencies
    command: cd functions && yarn install

deploy_firebase: &deploy_firebase
  run:
    name: Deploy Master to Firebase && deploy functions
    command: ./node_modules/.bin/firebase deploy --non-interactive --token=$FIREBASE_DEPLOY_TOKEN

restore_yarn_cache: &restore_yarn_cache
  restore_cache:
    keys:
    - node_modules-{{ checksum "yarn.lock" }}
    - node_modules

save_yarn_cache: &save_yarn_cache
  save_cache:
    key: node_modules-{{ checksum "yarn.lock" }}
    paths:
    - node_modules

restore_git_cache: &restore_git_cache
  restore_cache:
    keys:
    - generic-{{ .Branch }}-{{ .Revision }}
    - generic-{{ .Branch }}-
    - generic-

save_git_cache: &save_git_cache
  save_cache:
    key: generic-{{ .Branch }}-{{ .Revision }}
    paths:
    - ".git"

generic_build-procedure: &generic_build-procedure
  <<: *defaults
  steps:
  - <<: *upgrade_os
  - <<: *upgrade_yarn
  - <<: *restore_git_cache
  - checkout
  - <<: *save_git_cache
  - <<: *restore_yarn_cache
  - <<: *yarn_install
  - <<: *inspect_webpack_config
  - <<: *yarn_build
  - <<: *save_yarn_cache
  - persist_to_workspace:
      root: ~/bloqify
      paths:
      - generic

build_web1-procedure: &build_web1-procedure
  working_directory: ~/bloqify/web1
  docker:
  - image: circleci/node:10.7-stretch-browsers
  steps:
  - <<: *restore_git_cache
  - checkout
  - <<: *restore_yarn_cache
  - <<: *yarn_install
  - <<: *inspect_webpack_config
  - <<: *yarn_build
  - persist_to_workspace:
      root: ~/bloqify
      paths:
      - web1

lint-js-procedure: &lint-js-procedure
  <<: *defaults
  steps:
  - <<: *upgrade_os
  - <<: *upgrade_yarn
  - attach_workspace:
      at: ~/bloqify
  - <<: *eslint_junit
  - store_test_results:
      path: artefacts/eslint
  - store_artifacts:
      path: artefacts/eslint
      destination: eslint

test-jest-procedure: &test-jest-procedure
  <<: *defaults
  steps:
  - <<: *upgrade_os
  - <<: *upgrade_yarn
  - attach_workspace:
      at: ~/bloqify
  - <<: *yarn_test
  - store_test_results:
      path: artefacts/tests/jest
  - store_artifacts:
      path: artefacts/tests/jest
      destination: jest

deploy_web1-procedure: &deploy_web1-procedure
  working_directory: ~/bloqify/web1
  docker:
  - image: circleci/node:10.8-stretch-browsers
  steps:
    - attach_workspace:
        at: ~/bloqify
    - run:
        name: Create .firebaserc file
        command: 'echo ''{ "projects": { "default": "web1" } }'' > .firebaserc'
    - <<: *cloud_functions_yarn_install
    - <<: *deploy_firebase

jobs:
  generic_build:
    <<: *generic_build-procedure
  lint-js:
    <<: *lint-js-procedure
  test-jest:
    <<: *test-jest-procedure
  build_web1:
    <<: *build_web1-procedure
  deploy_web1:
    <<: *deploy_web1-procedure

workflows:
  version: 2
  build-test-deploy:
    jobs:
    - generic_build
    - lint-js:
        requires:
          - generic_build
    - test-jest:
        requires:
          - generic_build
    - build_web1:
        context: web1
        requires:
          - test-jest
          - lint-js
        filters:
          branches:
            only: master
    - deploy_web1:
        requires:
          - build_web1

```
