### ISSUE TITLE
Some styles are not minified correctly when not extracing

### ISSUE THREAD

**Issue by sqal** [vuejs/vue-cli#2954]
### Version
3.1.1

### Reproduction link
[https://github.com/sqal/vue-cli-css-minification-bug](https://github.com/sqal/vue-cli-css-minification-bug)

### Node and OS info
Node 10.11.0 / npm 6.4.1 / Windows 10

### Steps to reproduce
- Clone reproduction repository. It's just default template using latest cli version, I only turned off css extracting in `vue.config.js`
- Build project
- Serve built project, you can use browser-sync for that `npx browser-sync dist`
- Inspect injected styles in the head tag (the first one especially)

### What is expected?
All inline styles to be properly minified.

### What is actually happening?
Scoped styles from HelloWorld.vue component are not minified correctly. You should see similar output:

```css
h3[data-v-0495e2ba]{margin:40px 0 0
}
ul[data-v-0495e2ba]{list-style-type:none;padding:0
}
li[data-v-0495e2ba]{display:inline-block;margin:0 10px
}
a[data-v-0495e2ba]{color:#42b983
}
```

Note: This is not strictly related to scoped styles, because the same thing happens when using CSS modules.
