### ISSUE TITLE
Failed to find 'vue-cli-service' command in linux container on win 10 host

### ISSUE THREAD

**Issue by engblh** [vuejs/vue-cli#3506]
### Version
3.4.1

### Environment info
```
Linux container on windows 10 host
```

### Steps to reproduce
docker file
```
FROM node:latest

#ARG NODE_ENV
#ENV NODE_ENV=dev

ENV CONTAINER_PATH /var/www/myapp

WORKDIR $CONTAINER_PATH

COPY package*.json ./

# # install project dependencies
#RUN npm install -g @vue/cli-service-global
RUN npm install

#RUN yarn

EXPOSE 8080

# Start the app
CMD npm run serve
```

docker-compose.yml

```
version: '3'
services:
  web:
    container_name: myapp
    image: myapp
    build:
      context: .
      dockerfile: .docker/node.development.dockerfile
    volumes:
      - .:/var/www/myapp
    ports:
      - "8080:8080"
```

### What is expected?
when i run the app locally, ```vue-cli-service serve``` works. it should work in container as well

### What is actually happening?
vue-cli-service command not found

---
"@vue/cli-service": "^3.4.1", is part of dev-dependency

**Comment by sodatea** [comment]
Maybe related to this: https://cli.vuejs.org/guide/troubleshooting.html#running-installation-with-sudo-or-as-root ?

**Comment by engblh** [comment]
Thanks sodatea for reply.

I changed CMD to ```CMD npm_config_unsafe_perm=true vue-cli-service serve``` but still it did not work.

**Comment by engblh** [comment]
@LinusBorg how would i provide reproducible link for this issue. i have shared the docker file and compose file code here. Here is package.json looks like ```{
  "name": "myapp",
  "version": "0.1.0",
  "private": true,
  "description": "MyApp Description",
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build",
    "test:unit": "vue-cli-service test:unit",
    "test:e2e": "vue-cli-service test:e2e --mode=development"
  },
  "dependencies": {
    "@babel/helper-create-class-features-plugin": "^7.3.0",
    "@fortawesome/fontawesome-svg-core": "1.2.8",
    "@fortawesome/free-solid-svg-icons": "5.5.0",
    "@fortawesome/vue-fontawesome": "0.1.3",
    "axios": "0.18.0",
    "babel-polyfill": "^6.26.0",
    "canvas": "^2.3.1",
    "jspdf": "^1.5.3",
    "jspdf-autotable": "^3.0.5",
    "lodash": "4.17.11",
    "moment": "^2.24.0",
    "normalize.css": "8.0.1",
    "nprogress": "0.2.0",
    "vee-validate": "^2.1.7",
    "vue": "^2.6.7",
    "vue-json-excel": "^0.2.96",
    "vue-meta": "1.5.6",
    "vue-router": "3.0.2",
    "vue-split-panel": "^1.0.4",
    "vuetify": "^1.5.2",
    "vuex": "3.0.1",
    "vuex-router-sync": "^5.0.0"
  },
  "devDependencies": {
    "@babel/plugin-proposal-class-properties": "^7.3.3",
    "@vue/cli-plugin-babel": "^3.4.1",
    "@vue/cli-plugin-eslint": "^3.4.1",
    "@vue/cli-plugin-pwa": "^3.4.1",
    "@vue/cli-plugin-unit-jest": "^3.4.1",
    "@vue/cli-service": "^3.4.1",
    "@vue/eslint-config-prettier": "^4.0.0",
    "@vue/test-utils": "^1.0.0-beta.20",
    "babel-core": "7.0.0-bridge.0",
    "babel-eslint": "^10.0.1",
    "babel-jest": "^23.6.0",
    "cross-env": "5.2.x",
    "eslint": "^5.14.1",
    "eslint-plugin-vue": "^5.2.2",
    "express": "4.16.x",
    "flush-promises": "^1.0.2",
    "material-design-icons-iconfont": "^4.0.5",
    "node-sass": "^4.9.0",
    "prettier": "github:prettier/prettier#11f26a2",
    "sass-loader": "^7.0.1",
    "sinon": "^7.2.4",
    "stylus": "^0.54.5",
    "stylus-loader": "^3.0.1",
    "vue-cli-plugin-i18n": "^0.5.1",
    "vue-cli-plugin-vuetify": "^0.4.6",
    "vue-template-compiler": "^2.6.7",
    "vuepress": "^0.14.9",
    "vuetify-loader": "^1.2.1"
  },
  "engines": {
    "node": ">=8.9.0",
    "yarn": ">=1.0.0"
  },
}
```

**Comment by LinusBorg** [comment]
> how would i provide reproducible link for this issue.

Share a repo. That's the easiest and fasted way for us, and it makes sure we actually talk about the same code and settings etc.

But we can manage with the dockerfile i guess.

**Comment by engblh** [comment]
Hi @LinusBorg here is repository with docker file

https://github.com/engblh/docker-for-vue-dev

**Comment by sodatea** [comment]
😂 The problem lies in your dockerfile

1. You forgot to add this line `COPY . .` before serving the app. So the project files were not added to the container…
2. `vue-cli-service` is a project local command residing in `node_modules/.bin` so you need to run it with `npx vue-cli-service serve` or `npm run serve`
3. And you need to use the exec form of `CMD`: `CMD ["npm", "run", "serve"]`
4. And it's not recommended to set `NODE_ENV`  in your environment (https://cli.vuejs.org/guide/mode-and-env.html#modes) . Even if you do need, we use `development` rather than `dev` for dev builds.
5. Lastly, we need to expose the `node_modules` to the host by adding this to the `docker-compose.yml`:
```diff
    volumes:
      - .:/var/www/docker-vue
+     - /var/www/docker-vue/node_modules
```

------

Here's the full updated `docker-compse.yml`:
```yml
version: '3'
services:
  web:
    container_name: docker-vue
    image: docker-vue
    build:
      context: .
      dockerfile: .docker/node.development.dockerfile
    volumes:
      - .:/var/www/docker-vue
      - /var/www/docker-vue/node_modules
    environment:
      - npm_config_unsafe_perm=true
    ports:
      - "8080:8080"
```

dockerfile:
```dockerfile
FROM node:10.15.0

ENV CONTAINER_PATH /var/www/docker-vue

WORKDIR $CONTAINER_PATH

COPY package*.json ./

RUN npm install

COPY . .

EXPOSE 8080

CMD ["npm", "run", "serve"]
```
