### ISSUE TITLE
some css code will disappear when I build the project 

### ISSUE THREAD

**Issue by warwr1ck** [vuejs/vue-cli#367]
some CSS code will disapper when I run ``` npm run dev``` .
 when I build the whole project by using ```npm run build``` command the dist css do not contain some CSS code.

for example, a class named  ```.box```
```css
.box{
  display: -webkit-box;
  -webkit-box-orient: vertical;
  -webkit-box-pack: center;
  -webkit-box-align: center;
}
```
when I ```npm run dev``` and check the style in broswer(chrome). I can't find the ```-webkit-box-orient: vertical;``` 
when I ```npm run build``` the dist app.css file do no contain the ```-webkit-box-orient: vertical``` either. the others are still there
