### ISSUE TITLE
Project on vue-cli with postcss-normalize doesn't work properly

### ISSUE THREAD

**Issue by Yegorich555** [vuejs/vue-cli#4238]
### Version
3.8.4

### Reproduction link
[https://github.com/Yegorich555/FromScratch_VueJs/tree/feature/vuejs-cli/cli_test](https://github.com/Yegorich555/FromScratch_VueJs/tree/feature/vuejs-cli/cli_test)
The upper link contains a fixed (working) version. But bellow some explanations of the issue

### Environment info
```
 System:
    OS: Windows 10
    CPU: (12) x64 Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
  Binaries:
    Node: 11.10.0 - C:\Program Files\nodejs\node.EXE      
    Yarn: Not Found
    npm: 6.7.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.1.0
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0
    @vue/babel-plugin-transform-vue-jsx:  1.0.0
    @vue/babel-preset-app:  3.8.0
    @vue/babel-preset-jsx:  1.0.0
    @vue/babel-sugar-functional-vue:  1.0.0
    @vue/babel-sugar-inject-h:  1.0.0
    @vue/babel-sugar-v-model:  1.0.0
    @vue/babel-sugar-v-on:  1.0.0
    @vue/cli-overlay:  3.8.0
    @vue/cli-plugin-babel: ^3.8.0 => 3.8.0
    @vue/cli-plugin-eslint: ^3.8.0 => 3.8.0
    @vue/cli-service: ^3.8.0 => 3.8.4
    @vue/cli-shared-utils:  3.8.0
    @vue/component-compiler-utils:  2.6.0
    @vue/eslint-config-prettier: ^4.0.1 => 4.0.1
    @vue/preload-webpack-plugin:  1.1.0
    @vue/web-component-wrapper:  1.2.0
    eslint-plugin-vue: ^5.0.0 => 5.2.3 (4.7.1)
    vue: ^2.6.10 => 2.6.10
    vue-eslint-parser:  2.0.3 (5.0.0)
    vue-hot-reload-api:  2.3.3
    vue-loader:  15.7.0
    vue-router: ^3.0.3 => 3.0.6
    vue-style-loader:  4.1.2
    vue-template-compiler: ^2.6.10 => 2.6.10
    vue-template-es2015-compiler:  1.9.1
  npmGlobalPackages:
    @vue/cli: Not Found
```

### Steps to reproduce

1. Create the new default project with vue-cli (sass, postcss must be included)
2. Install [ **postcss-normalize** (npm)](https://www.npmjs.com/package/postcss-normalize)
3. Add config to **postcss.config.js** up to the following:

```javascript
module.exports = {
  plugins: {
    autoprefixer: {},
    "postcss-normalize": {
      forceImport: true
    }
  }
};
```
4. Update **.browserslistrc** to
``` 
> 1%
last 10 versions
```
5. build project

### What is expected?
```css
html { /*css-normalize at first */
       line-height: 1.15;
       -ms-text-size-adjust: 100%;
       -webkit-text-size-adjust: 100%
    }
/*there are no scope sections like html[data-v-78977f4a] */
    ...
#app { /*it is after the css-normalize*/
       font-family: Avenir, Helvetica, Arial, sans-serif;
       -webkit-font-smoothing: antialiased;
       -moz-osx-font-smoothing: grayscale;
       text-align: center;
       color: #2c3e50
    }
```

### What is actually happening?
```css
 #app {
       font-family: Avenir, Helvetica, Arial, sans-serif;
       -webkit-font-smoothing: antialiased;
       -moz-osx-font-smoothing: grayscale;
       text-align: center;
       color: #2c3e50
    }
    ...
    html[data-v-78977f4a] { /***this existense is wrong***/
       line-height: 1.15;
       -ms-text-size-adjust: 100%;
       -webkit-text-size-adjust: 100%
    }
    ...
    html {  /***this should be before #app***/
       line-height: 1.15;
       -ms-text-size-adjust: 100%;
       -webkit-text-size-adjust: 100%
    }
    ...
```

---
Removing any styles from **App.vue** fixes this issue - but it's not ok.
Using manual imports in main.js doesn't fix this issue - it's also wrong because the first line with 'import css' should be at first before others styles (after compilation)

Using of an additional style-block with 
```javascript
<style lang="postcss">
@import "normalize";
@import "sanitize";
</style>
```
(before any other style-blocks in **App.vue**) and removing **forceImport** from **postcss.config.js**
fixes this problem. But it's not ok.
