### ISSUE TITLE
cssnano options is not valid

### ISSUE THREAD

**Issue by leevscript** [vuejs/vue-cli#5044]
### Version
4.1.1

### Environment info
```
System:
    OS: macOS 10.15.2
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  Binaries:
    Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
    Yarn: Not Found
    npm: 6.13.4 - ~/.nvm/versions/node/v10.15.3/bin/npm
  Browsers:
    Chrome: 79.0.3945.88
    Firefox: Not Found
    Safari: 13.0.4
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0
    @vue/babel-plugin-transform-vue-jsx:  1.1.2
    @vue/babel-preset-app:  3.12.1
    @vue/babel-preset-jsx:  1.1.2
    @vue/babel-sugar-functional-vue:  1.1.2
    @vue/babel-sugar-inject-h:  1.1.2
    @vue/babel-sugar-v-model:  1.1.2
    @vue/babel-sugar-v-on:  1.1.2
    @vue/cli-plugin-babel: ^3.12.1 => 3.12.1
    @vue/cli-shared-utils:  3.12.1
    babel-helper-vue-jsx-merge-props:  2.0.3
    typescript: ^3.7.4 => 3.7.4
    vue: ^2.6.11 => 2.6.11
    vue-router:  3.1.3
    vue-touch:  2.0.0
  npmGlobalPackages:
    @vue/cli: 4.1.1
```

### Steps to reproduce
```css
/* app.css */
#app {
  min-width: initial;
}
```

```js
/* postcss.config.js */
module.exports = {
  plugins: [
    require('cssnano')({
      preset: ['default', {
        reduceInitial: false
      }]
    })
  ]
}
```

### What is expected?
```css
/* app.css */
#app {
  min-width: initial;
}
```

### What is actually happening?
```css
/* app.css */
#app {
  min-width: 0;
}
```
