### ISSUE TITLE
sh: 1: vue-cli-service: Permission denied 

### ISSUE THREAD

**Issue by MohMehrnia** [vuejs/vue-cli#5210]
I used Vue CLI to build vue project on GitHub actions like below:
```
name: ticket app CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [13.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install -g @vue/cli@latest
    - name: Build App
      working-directory: .
      run: |
        npm install
        npm run build
```
but the syntax runs with error and can not be complete.

```
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
added 1053 packages from 457 contributors, updated 17 packages and audited 31510 packages in 19.722s


38 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

sh: 1: vue-cli-service: Permission denied

npm ERR! code ELIFECYCLE
> aiki-helpdesk@0.1.0 build /home/runner/work/Aiki-HelpDesk/Aiki-HelpDesk
npm ERR! errno 126
> vue-cli-service build
npm ERR! aiki-helpdesk@0.1.0 build: `vue-cli-service build`

npm ERR! Exit status 126
npm ERR! 
npm ERR! Failed at the aiki-helpdesk@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2020-02-23T09_50_50_166Z-debug.log
##[error]Process completed with exit code 126.
```
