### ISSUE TITLE
`vue create app-name` throws an error and exits! 

### ISSUE THREAD

**Issue by shrihanDev** [vuejs/vue-cli#5943]
### Version
4.5.7

### Environment info
```
Environment Info:

  System:
    OS: Windows 7 6.1.7601
    CPU: (4) x64 Intel(R) Core(TM) i3 CPU       M 380  @ 2.53GHz
  Binaries:
    Node: 12.19.0 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 6.14.8 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 86.0.4240.75
  npmGlobalPackages:
    @vue/cli: Not Found
```

### Steps to reproduce
1. Run `vue create test-app`.
2. Get the following error:
```
 ERROR  TypeError: Cannot convert undefined or null to object
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at Object.exports.getFeatures (C:\Users\AnotherUser.APPLE.000\AppData\Roaming\npm\node_modules\@vue\cli\lib\util\features.js:14:26)
    at exports.formatFeatures (C:\Users\AnotherUser.APPLE.000\AppData\Roaming\npm\node_modules\@vue\cli\lib\util\features.js:23:28)
    at C:\Users\AnotherUser.APPLE.000\AppData\Roaming\npm\node_modules\@vue\cli\lib\Creator.js:429:34
    at Array.map (<anonymous>)
    at Creator.resolveIntroPrompts (C:\Users\AnotherUser.APPLE.000\AppData\Roaming\npm\node_modules\@vue\cli\lib\Creator.js:420:51)
    at new Creator (C:\Users\AnotherUser.APPLE.000\AppData\Roaming\npm\node_modules\@vue\cli\lib\Creator.js:55:50)
    at create (C:\Users\AnotherUser.APPLE.000\AppData\Roaming\npm\node_modules\@vue\cli\lib\create.js:71:19)
    at module.exports (C:\Users\AnotherUser.APPLE.000\AppData\Roaming\npm\node_modules\@vue\cli\lib\create.js:76:10)
    at Command.<anonymous> (C:\Users\AnotherUser.APPLE.000\AppData\Roaming\npm\node_modules\@vue\cli\bin\vue.js:81:29)
```

### What is expected?
Create a Vue app, asking some questions

### What is actually happening?
Getting the above error.

**Comment by shrihanDev** [comment]
>   npmGlobalPackages:
>       @vue/cli: Not Found
What does it mean? I  _do have_ installed @vue/cli using `npm install -g @vue/cli`

**Comment by sodatea** [comment]
What preset did you choose? What's in your `~/.vuerc` file?

**Comment by sodatea** [comment]
> What does it mean? I _do have_ installed @vue/cli using `npm install -g @vue/cli`

Could be a bug in https://github.com/tabrindle/envinfo, which the `vue info` command depends on.

**Comment by shrihanDev** [comment]
> What preset did you choose? What's in your `~/.vuerc` file?

Running `cat ~/.vuerc`:
```
{
  "useTaobaoRegistry": false,
  "latestVersion": "4.5.7",
  "lastChecked": 1602344356533,
  "presets": "{}"
}
```

**Comment by shrihanDev** [comment]
> > What does it mean? I _do have_ installed @vue/cli using `npm install -g @vue/cli`
> 
> Could be a bug in https://github.com/tabrindle/envinfo, which the `vue info` command depends on.

Running `sudo npm install -g envinfo && envinfo --npmGlobalPackages`:
```
npmGlobalPackages:
    @ionic/cli: 6.11.5
    @vue/cli: 4.5.6
    concurrently: 5.3.0
    electron-forge: 5.2.4
    electron-packager: 15.1.0
    envinfo: 7.7.3
    expo-cli: 3.22.3
    figlet-cli: 0.1.1
    generator-code: 1.2.24
    gitignore: 0.6.0
    less-watcher: 1.2.0
    less: 3.12.2
    nodemon: 2.0.4
    rimraf: 3.0.2
    typescript: 4.0.2
    yo: 3.1.1
```
