### ISSUE TITLE
CssNext / PostCss configuration doesn't work

### ISSUE THREAD

**Issue by archSeer** [vuejs/vue-cli#907]
### Version
3.0.0-beta.2

### Reproduction link
[https://gist.github.com/archSeer/a11ce5a9eda718573f0df5bc68d5af78](https://gist.github.com/archSeer/a11ce5a9eda718573f0df5bc68d5af78)

### Steps to reproduce
Compile.

### What is expected?
assets/styles.css to be processed and compiled to:

```css
div span { color: red }
```

.vue styles:

```css
div span { font-weight: 500 }
div { color: #fff }
```

### What is actually happening?
assets/styles.css isn't processed.

```css
div { & span { color: red } }
```

Styles / nesting inside the .vue component is processed, but the CSS variable I declared isn't processed by cssnext.

```css
div span { font-weight: 500 }
div { color: var(--white) }
```

---
I've configured this the same way I did on the vuejs-templates/webpack template on my other project: Installed postcss-cssnext and added it to the .postcssrc file.
